### ISSUE TITLE
php script not working

### ISSUE THREAD

**Issue by kmsomashekar** [chrisiaut/influxdb_radius_analyzer#2]
Hi,

I was trying to setup your tool for analyzing the NPS logs. After i execute the PHP i just see the command

[+ ]added 1602 and nothing happens

When i query the DB, it does not show any records. Please help me out.

**Comment by geek-at** [comment]
Hello!

Check the error log of your influxDB. The script might have problems with names with spaces in them.

On debian the log should be under /var/log/influxdb/error.log

**Comment by kmsomashekar** [comment]
Hi,

There is  no error.log created. However i see these lines in influxdb;log

[wal] 2016/02/25 17:14:42 Flush due to idle. Flushing 8 series with 8
points and 460 bytes from partition 1
[wal] 2016/02/25 17:14:42 write to index of partition 1 took 23.824436ms

Kindly help me out.

Regards,

Krishna M S

On Thu, Feb 25, 2016 at 5:04 PM, Christian Haschek <notifications@github.com

**Comment by geek-at** [comment]
Okay nothing suspicious here. Make sure the data is really sent to the server. You can use tcpdump on the linux box to verify that.

**Comment by kmsomashekar** [comment]
Hi,

When i do a a netstat -an on the server i see that the service is running
as udp6 instead of udp. Is that OK?

Regards,
Krishna M S

On Thu, Feb 25, 2016 at 5:27 PM, Christian Haschek <notifications@github.com

**Comment by geek-at** [comment]
yes that's ok

try it with `tcpdump udp port <your udp port>`

then start the php script and check if data is transmitted

**Comment by kmsomashekar** [comment]
Hi,

I see these

17:49:16.631405 IP trdxsrv31.toradex.int.54737 >
ittools-blr.toradex.int.8090: UDP, length 117
17:49:16.632201 IP trdxsrv31.toradex.int.54738 >
ittools-blr.toradex.int.8090: UDP, length 109

But it is not writing into the database.

Regards,

Krishna M S

On Thu, Feb 25, 2016 at 5:47 PM, Christian Haschek <notifications@github.com

**Comment by kmsomashekar** [comment]
Hi,

These are my settings

define('IMPORT_OLD',false);
define('USERADIUSTIME',true);
define('PATH',"C:\Windows\System32\LogFiles\IN");
define('DBNAME','radius');
define('DBIP','10.18.0.22');
define('DBPORT',8090);
define('ONLYNEWDATA',true);

The log files are under c:\windows\system32\LogFiles

Regards,

Krishna M S

On Thu, Feb 25, 2016 at 5:47 PM, Christian Haschek <notifications@github.com

**Comment by geek-at** [comment]
the new version now sanatizes strings before sending to influx, had problems with that before

**Comment by kmsomashekar** [comment]
Hi,

I tried to setup your tool again. When i run the command php
.\analyze_influx.php

I get this error

Warning: filesize(): stat failed for
C:\Windows\System32\LogFiles\IN1609.log in
C:\influxdb_radius_analyzer-master\analyze_influx.php on line 61

I am attaching the file for your reference. Please help me out

Regards,
Krishna M S

**Comment by kmsomashekar** [comment]
Hi,

FYI

The program gives the above error and runs into a infinite loop.

Regards,
Krishna M S

**Comment by geek-at** [comment]
Well have you checked that the file `C:\Windows\System32\LogFiles\IN1609.log``exists?

**Comment by kmsomashekar** [comment]
Hi,

I need a help from you. I downloaded the php file and tried to execute it.
The program executes well

However it does not close the Window. Is there a way to fix this problem. I
am running this on Windows 2012 R2 server with PHP 7.

Thank you

Regards,
Krishna M S
