### ISSUE TITLE
unable to parse : missing tag value

### ISSUE THREAD

**Issue by fr-lester** [chrisiaut/influxdb_radius_analyzer#3]
Hello Christian,
Nice job
I am testing your parser but i have an issue with it
The error is:
`[udp] 2016/07/18 01:24:03 Failed to parse points: unable to parse 'radius,type=accept,ap=cisco\ vwlc\ client,special=,special_type=OU value="domaine.com/society/100\ SOCIETY/01\ SIEGE\ SOCIAL/DIRECTION\ SERVICE\ INFORMATIQUE/0023\ SOCIETY\ DSI\ DIRECTION\ TECHNIQUE/FIRSNAME\ LASTNAME" 1468797843000000000': missing tag value`

UDP source is an Windows 2012R2 running NPS
Thank you for your help

System information:
Linux testing-box 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

Package: grafana
Architecture: amd64
Version: 3.1.0-1468321182

Package: influxdb
Architecture: amd64
Version: 0.13.0-1

**Comment by geek-at** [comment]
the problem seems to be the "special=". Tags can't be empty in InfluxDB

It's now fixed :)

**Comment by fr-lester** [comment]
Great 
Thank you Christian, now i can see data

Regards
