### ISSUE TITLE
Parser Radius Proxy

### ISSUE THREAD

**Issue by cafecraft** [chrisiaut/influxdb_radius_analyzer#5]
Hi,

I am having trouble getting the AP name when I use a Radius Proxy NPS in front of NPS with "analyze_influx.php", I changed the array from value 16 to 11 always returns me 0 when it enters case 2 (accept code 2). I have identified that it is a problem in the NPS log that does not register NAS Identifier: MAAP22-222 in field 11 when it is of type accept, have any solutions for this?

**Comment by geek-at** [comment]
Sorry, never heard of that problem or a Radius Proxy. You can send me the logs and I can try to figure it out but if it's a config thing for the NPS or proxy I probably can't help you.

But you might be interested in another tool I'm developing: [Electron Radius Parser](https://github.com/HaschekSolutions/electron-radius-parser). It will parse Radius files by dragging the log files onto the program, or it will look automatically if run from the NPS server
