### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'if' (T_IF) in C:\php\analyze_influx.php on line 122

### ISSUE THREAD

**Issue by vandwo** [chrisiaut/influxdb_radius_analyzer#7]
Hi chrisiaut,

I experience some PHP error after I try to run the script:
The error is:
`C:\php>php.exe analyze_influx.php
PHP Parse error:  syntax error, unexpected 'if' (T_IF) in C:\php\analyze_influx.php on line 122

Parse error: syntax error, unexpected 'if' (T_IF) in C:\php\analyze_influx.php on line 122`

1. My NPS Role is on Server 2019 (I don' think this matter since the log format is the same as older versions

2: My PHP Version is php-7.3.6 (tried also with older version same issue)

3: My Configuration is as following:
`define('IMPORT_OLD',true);
define('USERADIUSTIME',true);
define('PATH',"C:\\logs\\radius-nps\\IN");
define('DBNAME','radius');
define('DBIP','192.168.X.X);
define('DBPORT',8090);
define('ONLYNEWDATA',true);
define('DAILYLOGS',false);`

I'm not sure but I think the error is caused by the .php code? Should I run it with specific PHP version that you can recommend? 

Thanks!
BR,
Ivan

**Comment by vandwo** [comment]
Hi,

Found out that I need to run it with php-win.exe and it passed without error on windows.
But still no data was transferred to the influxDB. Further troubleshooting will be done

**Comment by KraftyMac** [comment]
Did you ever figure this out? I experienced the same error and ran it as php-win as you did, but still I don't see any data. Where do we put this to keep it running?

**Comment by fastxl** [comment]
I get the same, no data in database. Tried to create the database first and still no data.
